import os

# 项目根目录
ENTRY_STORAGE_PATH = os.path.join(".", "storage")

# 数据库配置
DATABASE_DRIVER = "postgresql"
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "123456"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_NAME = "ide"

# 数据库连接 URL
DATABASE_CONNECTION_URL = f"{DATABASE_DRIVER}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}"
DATABASE_ADMIN_URL = f"{DATABASE_CONNECTION_URL}/postgres"
DATABASE_URL = f"{DATABASE_CONNECTION_URL}/{DATABASE_NAME}"
