import os

# 项目存储路径
STORAGE_PATH = os.path.join(os.path.dirname(__file__), "storage")

# 数据库配置
DATABASE_ENGINE = "postgresql"
DATABASE_DRIVER = "asyncpg"
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "123456"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_NAME = "ide"

# 数据库连接 URL
DATABASE_CONNECTION_URL = f"{DATABASE_ENGINE}+{DATABASE_DRIVER}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}"
DATABASE_ADMIN_URL = f"{DATABASE_CONNECTION_URL}/postgres"
DATABASE_URL = f"{DATABASE_CONNECTION_URL}/{DATABASE_NAME}"

# 加密配置
ENCRYPT_KEY = "smlwyhwxhfstwzx"  # 秘钥
ENCRYPT_JWT_ALGO = "HS256"  # 算法
