import os

# 服务器配置
SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8080

# 项目存储路径
STORAGE_PATH = os.path.join(os.path.dirname(__file__), "..", "storage")

# 数据库配置
DATABASE_ENGINE = "postgresql"
DATABASE_DRIVER = "asyncpg"
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "123456"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_NAME = "ide"
DATABASE_CONNECTION_URL = f"{DATABASE_ENGINE}+{DATABASE_DRIVER}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}"
DATABASE_ADMIN_URL = f"{DATABASE_CONNECTION_URL}/postgres"
DATABASE_URL = f"{DATABASE_CONNECTION_URL}/{DATABASE_NAME}"

# 缓存配置
CACHE_ENGINE = "redis"
CACHE_USER = ""
CACHE_PASSWORD = "123456"
CACHE_HOST = "localhost"
CACHE_PORT = "6379"
CACHE_URL = f"{CACHE_ENGINE}://{CACHE_USER}:{CACHE_PASSWORD}@{CACHE_HOST}:{CACHE_PORT}"

# docker配置
DOCKER_HOST = "localhost"
DOCKER_PORT = "2375"
DOCKER_URL = f"tcp://{DOCKER_HOST}:{DOCKER_PORT}"
DOCKER_CONTAINER_POSTGRESQL_NAME = "software-engineering-project-postgres"
DOCKER_CONTAINER_REDIS_NAME = "software-engineering-project-redis"

# 加密配置
AUTH_JWE_ALG = "A256KW"
AUTH_JWE_ENC = "A256CBC-HS512"

# 邮箱配置
SMTP_SERVER = 'smtp.qq.com'
SMTP_PORT = 465
SMTP_USER = 'fsht12345@qq.com'
SMTP_PASSWORD = 'eflyqjkfcfdugfed'
